const SportsData = [
	{
		id: 1,
		first_name: 'FAWAZ ',
		last_name: 'ALQARNI',
		dateOfBirth: '02-04-1992',
		gender: 'Male',
		salary: 4.24,
		position: 'Goalkeeper',
		playerPhoto: 'https://www.saff.com.sa/uploadcenter/saffplayer1567509064.jpg',
	},
	{
		id: 2,
		first_name: 'Mohammed ',
		last_name: 'ALOWAIS',
		dateOfBirth: '10-10-1991',
		gender: 'Male',
		salary: 6.15,
		position: 'Goalkeeper',
		playerPhoto: 'https://www.saff.com.sa/uploadcenter/saffplayer1567508503.jpg',
	},
	{
		id: 3,
		first_name: 'Mohammed ',
		last_name: 'Alyami',
		dateOfBirth: '14-08-1997',
		gender: 'Male',
		salary: 2.75,
		position: 'Goalkeeper',
		playerPhoto: 'https://www.saff.com.sa/uploadcenter/saffplayer1574936451.jpg',
	},
	{
		id: 4,
		first_name: 'Zaid ',
		last_name: 'ALBAWARDI',
		dateOfBirth: '26-01-1997',
		gender: 'Male',
		salary: 4.88,
		position: 'Goalkeeper',
		playerPhoto: 'https://www.saff.com.sa/uploadcenter/saffplayer1623235799.jpg',
	},
	{
		id: 5,
		first_name: 'Abdulelah ',
		last_name: 'Alamri',
		dateOfBirth: '15-01-1997',
		gender: 'Male',
		salary: 5.15,
		position: 'Defender',
		playerPhoto: 'https://www.saff.com.sa/uploadcenter/saffplayer1577863020.jpg',
	},
	{
		id: 6,
		first_name: 'Mohammed ',
		last_name: 'ALBURAYK',
		dateOfBirth: '15-09-1992',
		gender: 'Male',
		salary: 7.15,
		position: 'Defender',
		playerPhoto: 'https://www.saff.com.sa/uploadcenter/saffplayer1570138016.jpg',
	},
	{
		id: 7,
		first_name: 'Sultan ',
		last_name: 'Alghanam',
		dateOfBirth: '25-05-1992',
		gender: 'Male',
		salary: 2.24,
		position: 'Defender',
		playerPhoto: 'https://www.saff.com.sa/uploadcenter/saffplayer1567508341.jpg',
	},
	{
		id: 8,
		first_name: 'Abdulelah ',
		last_name: 'ALMALKI',
		dateOfBirth: ' 11-10-1994',
		gender: 'Male',
		salary: 2.69,
		position: 'Midfielder',
		playerPhoto: 'https://www.saff.com.sa/uploadcenter/saffplayer1573934672.jpeg',
	},
	{
		id: 9,
		first_name: 'Ali ',
		last_name: 'ALASMARI',
		dateOfBirth: '12-01-1997',
		gender: 'Male',
		salary: 8.91,
		position: 'Midfielder',
		playerPhoto: 'https://www.saff.com.sa/uploadcenter/saffplayer1623235864.jpg',
	},
	{
		id: 10,
		first_name: 'Saleh ',
		last_name: 'ALSHEHRI',
		dateOfBirth: ' 01-11-1993',
		gender: 'Male',
		salary: 20.7,
		position: 'Striker',
		playerPhoto: 'https://www.saff.com.sa/uploadcenter/saffplayer1623235746.jpg',
	},
	{
		id: 11,
		first_name: 'FAWAZ ',
		last_name: 'ALQARNI',
		dateOfBirth: '02-04-1992',
		gender: 'Male',
		salary: 4.24,
		position: 'Goalkeeper',
		playerPhoto: 'https://www.saff.com.sa/uploadcenter/saffplayer1567509064.jpg',
	},
	{
		id: 12,
		first_name: 'Mohammed ',
		last_name: 'ALOWAIS',
		dateOfBirth: '10-10-1991',
		gender: 'Male',
		salary: 6.15,
		position: 'Goalkeeper',
		playerPhoto: 'https://www.saff.com.sa/uploadcenter/saffplayer1567508503.jpg',
	},
	{
		id: 13,
		first_name: 'Mohammed ',
		last_name: 'Alyami',
		dateOfBirth: '14-08-1997',
		gender: 'Male',
		salary: 2.75,
		position: 'Goalkeeper',
		playerPhoto: 'https://www.saff.com.sa/uploadcenter/saffplayer1574936451.jpg',
	},
	{
		id: 14,
		first_name: 'Zaid ',
		last_name: 'ALBAWARDI',
		dateOfBirth: '26-01-1997',
		gender: 'Male',
		salary: 4.88,
		position: 'Goalkeeper',
		playerPhoto: 'https://www.saff.com.sa/uploadcenter/saffplayer1623235799.jpg',
	},
	{
		id: 15,
		first_name: 'Abdulelah ',
		last_name: 'Alamri',
		dateOfBirth: '15-01-1997',
		gender: 'Male',
		salary: 5.15,
		position: 'Defender',
		playerPhoto: 'https://www.saff.com.sa/uploadcenter/saffplayer1577863020.jpg',
	},
	{
		id: 16,
		first_name: 'Mohammed ',
		last_name: 'ALBURAYK',
		dateOfBirth: '15-09-1992',
		gender: 'Male',
		salary: 7.15,
		position: 'Defender',
		playerPhoto: 'https://www.saff.com.sa/uploadcenter/saffplayer1570138016.jpg',
	},
	{
		id: 17,
		first_name: 'Sultan ',
		last_name: 'Alghanam',
		dateOfBirth: '25-05-1992',
		gender: 'Male',
		salary: 2.24,
		position: 'Defender',
		playerPhoto: 'https://www.saff.com.sa/uploadcenter/saffplayer1567508341.jpg',
	},
	{
		id: 18,
		first_name: 'Abdulelah ',
		last_name: 'ALMALKI',
		dateOfBirth: ' 11-10-1994',
		gender: 'Male',
		salary: 2.69,
		position: 'Midfielder',
		playerPhoto: 'https://www.saff.com.sa/uploadcenter/saffplayer1573934672.jpeg',
	},
	{
		id: 19,
		first_name: 'Ali ',
		last_name: 'ALASMARI',
		dateOfBirth: '12-01-1997',
		gender: 'Male',
		salary: 8.91,
		position: 'Midfielder',
		playerPhoto: 'https://www.saff.com.sa/uploadcenter/saffplayer1623235864.jpg',
	},
	{
		id: 20,
		first_name: 'Saleh ',
		last_name: 'ALSHEHRI',
		dateOfBirth: ' 01-11-1993',
		gender: 'Male',
		salary: 20.7,
		position: 'Striker',
		playerPhoto: 'https://www.saff.com.sa/uploadcenter/saffplayer1623235746.jpg',
	},
];

export default SportsData;
